// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxseikvywzqnviiqmphb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4c2Vpa3Z5d3pxbnZpaXFtcGhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNDM2MzgsImV4cCI6MjA2MzYxOTYzOH0.Z04Z1080-C2wexiEEvr9jIfiJgh7OrK3Tx5YG2sY7E0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);